@Web_HostAddress = http://localhost:5125

### Get Spanish Greeting
GET http://localhost:5125/get-spanish-greeting?name=Temporal
Content-Type: application/json

###

### Get Spanish Farewell
GET http://localhost:5125/get-spanish-farewell?name=JwahirS
Content-Type: application/json


