name: Continuous Integration
on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"
permissions:
  contents: read

jobs:
  build-lint-test:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            checkTarget: true
          - os: ubuntu-latest
    runs-on: ${{ matrix.runsOn || matrix.os }}
    steps:
      - name: Print build information
        run: "echo head_ref: ${{ github.head_ref }}, ref: ${{ github.ref }}, os: ${{ matrix.os }}"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8

      - name: Build
        run: dotnet build
        working-directory: exercises/hello-workflow/solution/Worker

      - name: Build
        run: dotnet build
        working-directory: exercises/farewell-workflow/solution/Worker

      - name: Check format
        if: ${{ matrix.checkTarget }}
        run: dotnet format --verify-no-changes
        working-directory: exercises/hello-workflow/solution/Worker

      - name: Check format
        if: ${{ matrix.checkTarget }}
        run: dotnet format --verify-no-changes
        working-directory: exercises/farewell-workflow/solution/Worker
